In [18]:
name = input("State your name: ")
print("hello %s" % (name,))

hello sarah


In [25]:
dt.datetime(year=2018,month=9,day=28,hour=18,minute=00)

datetime.datetime(2018, 9, 28, 18, 0)

In [29]:
import datetime as dt
now = dt.datetime.now()
print(now.hour)

17


In [41]:
name = input("State your name: ")
if (now.hour < 12):
    time = 'morning'
else:
    time = 'evening'
print("good %s, %s" % (time,name,))

good evening, sarah


In [45]:
str3 = 'hallo world'
str3.strip()
#strip removes empty space or \n

'hallo world'

In [46]:
str3.strip('d')
#or last letter

'hallo worl'

In [48]:
str3.split('l')

['ha', '', 'o wor', 'd']

In [52]:
import numpy as np
arr1 = np.arange(1,11)

In [53]:
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [55]:
arr1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [56]:
arr1[-1::-2]

array([10,  8,  6,  4,  2])

In [60]:
arr1[1::2]

array([ 2,  4,  6,  8, 10])